#ifndef RACERPROFILEMACROS_H
#define RACERPROFILEMACROS_H

#define TORTOISENAME "The Tortoise"
#define TORTOISEASCIIFILENAME "res/images/tortoise.png"
#define TORTOISESPEED 15
#define TORTOISESTAMINA 100
#define TORTOISEREACTIONSEC 0
#define TORTOISEREACTIONNSEC 600000000
#define TORTOISERESTTIMESEC 1
#define TORTOISERESTTIMENSEC 0

#define HARENAME "The Hare"
#define HAREASCIIFILENAME "res/images/hare.png"
#define HARESPEED 20
#define HARESTAMINA 60
#define HAREREACTIONSEC 0
#define HAREREACTIONNSEC 100000000
#define HARERESTTIMESEC 2
#define HARERESTTIMENSEC 200000000

#endif